// LOCALHOST
###
// API Docs
GET http://localhost:8080/api-docs/
###
GET http://localhost:8080/movies/
###
GET http://localhost:8080/movies/640d4dd9a2a3dfbbfe5b555d
###
GET http://localhost:8080/movies/640d4d346b3e407bbc14d6b9
###
GET http://localhost:8080/movies/63ba4c01de71fc903c458f85
###
// Create contact
POST http://localhost:8080/movies/ HTTP/1.1 
content-type: application/json

{
    "title": "Back To The Future",
    "releaseYear": "1984",
    "genre": "Sci-fi",
    "director": "Robert Zemeckis",
    "rating": "G",
    "writer": "Robert Zemeckis",
    "cinematographer": "Dean Cundey"
}

###
// Update Contact
PUT http://localhost:8080/movies/640d4c9b6b3e407bbc14d6b8
content-type: application/json

{
    "title": "Back To The Future",
    "releaseYear": "1985",
    "genre": "Sci-fi",
    "director": "Robert Zemeckis",
    "rating": "PG",
    "writer": "Robert Zemeckis",
    "cinematographer": "Dean Cundey"
}

###
//Delete Contact

DELETE http://localhost:8080/movies/640d4c9b6b3e407bbc14d6b8




// ==================================================


// PRODUCTION Deploy
###
// API Docs
GET https://chase-cse341-movieapi.onrender.com/api-docs/
###
GET https://chase-cse341-movieapi.onrender.com/movies/
###
GET https://chase-cse341-movieapi.onrender.com/movies/640d4dd9a2a3dfbbfe5b555d
###
GET https://chase-cse341-movieapi.onrender.com/movies/640d4d346b3e407bbc14d6b9
###
GET https://chase-cse341-movieapi.onrender.com/movies/63ba4c01de71fc903c458f85


###
// Create contact
POST http://chase-cse341-movieAPI/movies/ HTTP/1.1 
content-type: application/json

{
    "title": "Back To The Future",
    "releaseYear": "1984",
    "genre": "Sci-fi",
    "director": "Robert Zemeckis",
    "rating": "G",
    "writer": "Robert Zemeckis",
    "cinematographer": "Dean Cundey"
}

###
// Update Contact
PUT http://chase-cse341-movieAPI/movies/640d4c9b6b3e407bbc14d6b8
content-type: application/json

{
    "title": "Back To The Future",
    "releaseYear": "1985",
    "genre": "Sci-fi",
    "director": "Robert Zemeckis",
    "rating": "PG",
    "writer": "Robert Zemeckis",
    "cinematographer": "Dean Cundey"
}

###
//Delete Contact

DELETE https://chase-cse341-movieAPI.onrender.com/contacts/640041106aee23b65f2c425b